"""empty message

Revision ID: c548e76fcf8f
Revises: 0763d677d453
Create Date: 2026-01-24 00:01:36.030136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c548e76fcf8f'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types
    role_enum = sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=False),
                    sa.Column('admin_id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('reading',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('content', sa.String(
                        length=1000), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('student_group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('todo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=False),
                    sa.Column('due_date', sa.Date(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(
                        ['student_id'], ['student_group.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('submission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=False),
                    sa.Column('response_url', sa.String(
                        length=300), nullable=False),
                    sa.Column('todo_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['student_id'], ['student_group.id'], ),
                    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('submission_id', sa.Integer(), nullable=False),
                    sa.Column('state', sa.Enum('PENDING', 'APPROVED',
                                               'REJECTED', name='status_enum'), nullable=False),
                    sa.Column('feedback', sa.String(
                        length=255), nullable=False),
                    sa.Column('teachers_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['submission_id'], ['submission.id'], ),
                    sa.ForeignKeyConstraint(['teachers_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum(
            'ADMIN', 'TEACHER', 'STUDENT', name='role_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    op.drop_table('status')
    op.drop_table('submission')
    op.drop_table('todo')
    op.drop_table('student_group')
    op.drop_table('reading')
    op.drop_table('group')

    # Drop ENUM types
    role_enum = sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role_enum')
    role_enum.drop(op.get_bind(), checkfirst=True)

    status_enum = sa.Enum('PENDING', 'APPROVED',
                          'REJECTED', name='status_enum')
    status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table('group')
    # ### end Alembic commands ###
