"""empty message

Revision ID: d3c003d31458
Revises: c548e76fcf8f
Create Date: 2026-01-24 00:17:59.409895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c003d31458'
down_revision = 'c548e76fcf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('status_teachers_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('teachers_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teachers_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('status_teachers_id_fkey'), 'user', ['teachers_id'], ['id'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
