"""empty message

Revision ID: fa8d44fdab84
Revises: 9bef3b5ac0da
Create Date: 2026-02-09 12:39:36.644571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8d44fdab84'
down_revision = '9bef3b5ac0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('reading_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('response_url',
                              existing_type=sa.VARCHAR(length=300),
                              type_=sa.String(length=500),
                              existing_nullable=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('archive_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('archive_url')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('response_url',
                              existing_type=sa.String(length=500),
                              type_=sa.VARCHAR(length=300),
                              existing_nullable=False)

    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_column('reading_url')

    # ### end Alembic commands ###
